# permissions for end users to view rotations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rotation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kb
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
  name: rotation-viewer-role
rules:
- apiGroups:
  - api.g8s.io
  resources:
  - rotations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.g8s.io
  resources:
  - rotations/status
  verbs:
  - get
